# Generated by Django 5.0.6 on 2024-05-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyandu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], help_text='Género con el que se autopersive el empleado.', max_length=1),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
